// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Todo struct {
	TodoID string `json:"todoID"`
	Title  string `json:"title"`
	Text   string `json:"text"`
}

type TodoInput struct {
	Title string `json:"title"`
	Text  string `json:"text"`
}
